[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-dev',
    'npm ci --include=dev'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan storage:link',
    'php artisan config:clear',
    'php artisan cache:clear',
    'php artisan route:clear',
    'php artisan view:clear'
]

[env]
NIXPACKS_PHP_ROOT_DIR = '/app/public'
NIXPACKS_PHP_FALLBACK_PATH = '/index.php'
