[phases.setup]
nixpkgs = ["php83", "php83Packages.composer", "nodejs_20"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm ci", "npm run build"]

[phases.build]
cmds = [
  "mkdir -p storage/framework/views storage/framework/cache storage/logs"
]
