[phases.setup]
nixPkgs = ['nodejs', 'php83', 'php83Packages.composer']
nixLibs = ['php83Extensions.pdo_mysql', 'php83Extensions.mysqli']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-dev',
    'npm ci --include=dev'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:clear',
    'php artisan cache:clear',
    'php artisan route:clear',
    'php artisan view:clear'
]

[start]
cmd = 'php -c php.ini artisan serve --host=0.0.0.0 --port=${PORT:-8080}'
